# use vi-mode in tmux
set-window-option -g mode-keys vi

# set prefix from C-b to C-a
set -g prefix C-a
# unbind the original C-b prefix keybinding
unbind C-b

# set shorter delay between prefix and command
set -s escape-time 1

# make it easier to reload configuration
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# allow prefix to pass through
bind C-a send-prefix

# split panes with more semantic binds
bind | split-window -h
bind - split-window -v

# use vim-style navigation for panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# use vim-style navigation for windows
# (note): `-r` makes it repeatable
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# use vim-style copy/yank
bind-key -T copy-mode-vi 'y' send-keys -X copy-selection

# load plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# install tpm if not already present
if "test ! -d ~/.tmux/plugins/tpm" \
    "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/bin/install_plugins'"

# initialize tmux plugin manager (needs to be at bottom)
run -b '~/.tmux/plugins/tpm/tpm'
