import = ["/home/anson/.config/alacritty/FrontEndDelight.toml"]

[cursor]
blink_interval = 500

[cursor.style]
blinking = "Off"
shape = "Beam"

[font]
size = 10.0

[font.normal]
family = "MesloLGS NF"

[scrolling]
history = 100000

[window]
# decorations = "none"
opacity = 0.9
startup_mode = "Windowed"

[window.dimensions]
columns = 100
lines = 30

[bell]
animation = "Ease"
duration = 1
