import = ["/home/anson/.config/alacritty/gruvbox_dark_hard.toml"]

[cursor]
blink_interval = 500

[cursor.style]
blinking = "Off"
shape = "Beam"

[font]
size = 10.0

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.italic]
style = "Italic"

[font.bold]
style = "Bold"

[scrolling]
history = 100000

[window]
# decorations = "none"
opacity = 0.9
startup_mode = "Windowed"

[window.dimensions]
columns = 100
lines = 30

[bell]
animation = "Ease"
duration = 1
